
# Trying this on face experssion data 
artifacts_root: /Users/sultanalyami/Desktop/TrackVision_Project/TrackVision/artifacts 

data_ingestion : 
    root_dir : /Users/sultanalyami/Desktop/TrackVision_Project/TrackVision/artifacts/data_ingestion
    source_url : https://github.com/Sultanahmed-99/TrackVision/raw/main/archive%202.zip
    local_data_file : /Users/sultanalyami/Desktop/TrackVision_Project/TrackVision/artifacts/data_ingestion/data.zip
    unzip_file : /Users/sultanalyami/Desktop/TrackVision_Project/TrackVision/artifacts/data_ingestion
      



preaper_base_model : 
    root_dir :  /Users/sultanalyami/Desktop/TrackVision_Project/TrackVision/artifacts/preaper_base_model
    base_model_path : /Users/sultanalyami/Desktop/TrackVision_Project/TrackVision/artifacts/preaper_base_model/base_model.h5
    update_base_model_path : /Users/sultanalyami/Desktop/TrackVision_Project/TrackVision/artifacts/preaper_base_model/base_model_updated.h5


preaper_callbacks : 
    root_dir :  /Users/sultanalyami/Desktop/TrackVision_Project/TrackVision/artifacts/preaper_callbacks
    tensrboard_root_log_dir : /Users/sultanalyami/Desktop/TrackVision_Project/TrackVision/artifacts/preaper_callbacks/tensorboard_log_dir
    checkpoint_model_filepath: /Users/sultanalyami/Desktop/TrackVision_Project/TrackVision/artifacts/checkpoint_dir/model.h5



training : 
    root_dir :  /Users/sultanalyami/Desktop/TrackVision_Project/TrackVision/artifacts/training
    trained_model_path : /Users/sultanalyami/Desktop/TrackVision_Project/TrackVision/artifacts/training/model.h5
    

